In [3]:
# import pandas and numpy library
import pandas as pd
import numpy as np

In [4]:
#reading the dataset "Entertainer_data.csv" and storing it in a dataframe
#using pd.read_csv() function
df=pd.read_csv('/content/Entertainer_data.csv')

In [5]:
#displaying top 5 rows of the dataset
df.head(5)

,Entertainer,Gender (traditional),Birth Year,Year of Breakthrough/#1 Hit/Award Nomination,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,2008,19,2009.0,2016,NaN
1,Angelina Jolie,F,1975,1999,"Girl, Interrupted",1999.0,2016,NaN
2,Aretha Franklin,F,1942,1967,I Never Loved a Man (The Way I Love You),1968.0,2014,NaN
3,Bette Davis,F,1908,1934,Of Human Bondage,1935.0,1989,1989.0
4,Betty White,F,1922,1952,Life with Elilzabeth,1976.0,2016,NaN

In [6]:
#checking the datatypes of all the columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 8 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Entertainer                                   69 non-null     object
 1   Gender (traditional)                          69 non-null     object
 2   Birth Year                                    69 non-null     int64
 3   Year of Breakthrough/#1 Hit/Award Nomination  69 non-null     int64
 4   Breakthrough Name                             69 non-null     object
 5   Year of First Oscar/Grammy/Emmy               63 non-null     float64
 6   Year of Last Major Work (arguable)            69 non-null     int64
 7   Year of Death                                 30 non-null     float64
dtypes: float64(2), int64(3), object(3)
memory usage: 4.4+ KB

In [8]:
#change Year of Breakthrough/#1 Hit/Award Nomination column name as Year of Breakthrough and Gender (traditional) as Gender
df.rename(columns={'Year of Breakthrough/#1 Hit/Award Nomination':'Year of Breakthrough','Gender (traditional)':'Gender'},inplace=True)
#displaying top 5 rows after changing the column names
df.head(5)

,Entertainer,Gender,Birth Year,Year of Breakthrough,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,2008,19,2009.0,2016,NaN
1,Angelina Jolie,F,1975,1999,"Girl, Interrupted",1999.0,2016,NaN
2,Aretha Franklin,F,1942,1967,I Never Loved a Man (The Way I Love You),1968.0,2014,NaN
3,Bette Davis,F,1908,1934,Of Human Bondage,1935.0,1989,1989.0
4,Betty White,F,1922,1952,Life with Elilzabeth,1976.0,2016,NaN

In [9]:
# check null values

df.isnull().sum()

Entertainer                            0
Gender                                 0
Birth Year                             0
Year of Breakthrough                   0
Breakthrough Name                      0
Year of First Oscar/Grammy/Emmy        6
Year of Last Major Work (arguable)     0
Year of Death                         39
dtype: int64

In [11]:
#Column 'Year of first Oscar/Grammy/Emmy has some blank spaces. Relaced them with NA

df['Year of First Oscar/Grammy/Emmy'].fillna('NA', inplace=True)

In [12]:
#Column 'Year of Death' has some blank spaces. Relaced them with a placeholder 'Still Alive'
df['Year of Death'].fillna('Still Alive', inplace=True)

In [13]:
# displaying top 5 row
df.head(5)

,Entertainer,Gender,Birth Year,Year of Breakthrough,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death
0,Adele,F,1988,2008,19,2009.0,2016,Still Alive
1,Angelina Jolie,F,1975,1999,"Girl, Interrupted",1999.0,2016,Still Alive
2,Aretha Franklin,F,1942,1967,I Never Loved a Man (The Way I Love You),1968.0,2014,Still Alive
3,Bette Davis,F,1908,1934,Of Human Bondage,1935.0,1989,1989.0
4,Betty White,F,1922,1952,Life with Elilzabeth,1976.0,2016,Still Alive

In [14]:
#checking null values after replacing them

df.isnull().sum()

Entertainer                           0
Gender                                0
Birth Year                            0
Year of Breakthrough                  0
Breakthrough Name                     0
Year of First Oscar/Grammy/Emmy       0
Year of Last Major Work (arguable)    0
Year of Death                         0
dtype: int64

In [15]:
#Created a new column 'Age at Breakthrough' which is 'Year of Breakthrough' subtracting 'Birth Year'.

df['Age at Breakthrough']=df['Year of Breakthrough']-df['Birth Year']

In [17]:
#Created another column 'Active Years' which is 'Year of Last Major Work' subtracting 'Year of Breakthrough'

df['Active Years']=df['Year of Last Major Work (arguable)']-df['Year of Breakthrough']

#displaying top 5 rows of the dataset
df.head(5)

,Entertainer,Gender,Birth Year,Year of Breakthrough,Breakthrough Name,Year of First Oscar/Grammy/Emmy,Year of Last Major Work (arguable),Year of Death,Age at Breakthrough,Active Years
0,Adele,F,1988,2008,19,2009.0,2016,Still Alive,20,8
1,Angelina Jolie,F,1975,1999,"Girl, Interrupted",1999.0,2016,Still Alive,24,17
2,Aretha Franklin,F,1942,1967,I Never Loved a Man (The Way I Love You),1968.0,2014,Still Alive,25,47
3,Bette Davis,F,1908,1934,Of Human Bondage,1935.0,1989,1989.0,26,55
4,Betty White,F,1922,1952,Life with Elilzabeth,1976.0,2016,Still Alive,30,64

In [19]:
#

df.to_csv('Entertainer_cleaned_data.csv', index=False)